### ISSUE TITLE
Feature request - copy link to game page

### ISSUE THREAD

**Issue by nine9ths** [Marlon154/boardgame-search#3]
Cool plugin, it does a good job of importing games into a vault!

I'm wondering if you would consider adding an option to the search to just copy as markdown a link to a boardgame page with or without the image. Or maybe insert at the cursor. I keep notes of games I want to check out, but don't necessarily want all their data in my vault.

Thanks for considering!

**Comment by Marlon154** [comment]
Hello,

I do not plan to implement such a feature, but definitely would merge a PR which implements it.
There **may** be also a workaround using templater and something like:
- creating the note with url
- copy the url to the clipboard
- deleting the note

If you give it a try, let me know whether it worked.

**Comment by nine9ths** [comment]
I played around with trying to implement this but ended up going with a web clipper template + css snippet instead. I just use the "Copy to clipboard" command rather than "Add to Obsidian". This was probably a better fit for my workflow anyway.

Here's the settings I ended up using for completeness sake:
```json
{
  "schemaVersion": "0.1.0",
  "name": "BGG Link",
  "behavior": "create",
  "noteContentFormat": "> [!BGG] [{{title}}]({{url}})\n> [![]({{image}})]({{url}}) {{description}}\n\n",
  "properties": [],
  "triggers": [
    "boardgamegeek.com"
  ],
  "noteNameFormat": "{{title}}",
  "path": "Clippings"
}
```

```css
.callout[data-callout="bgg"] {
    --callout-color: 63, 58, 96;
    --callout-icon: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 23 38"><path fill="#FF5100" stroke="#FF5100" d="m24.87 7.01-3.763 1.025L24.792 0 .9 8.794l1.306 10.533L0 21.454 6.577 37.93l13.981-5.151 4.86-11.409-2.087-2.012z"/></svg>'
}

.callout[data-callout="bgg"] a {
    background-image: none;
    color: white;
    padding-inline-end: 0;
}

.callout[data-callout="bgg"] img {
    float:left;
    margin-right: 0.9em;
    margin-bottom: 0.9em;
    max-width: 40%;
    vertical-align: top;
    margin-top: 0;
}
```

Thanks for considering the request!
